---
config:
  layout: elk
---
erDiagram
	direction LR
  subscription }o--|| organization : "organization_id"
  invoice      }o--|| subscription : "subscription_id"
  payment      }o--|| invoice      : "invoice_id"
  certificate  }o--|| account      : "account_id"
  profile      ||--|| account      : "account_id"
  plan         ||--o{ subscription : "plan_id"
  credential   |o--|| account      : "account_id"
  account      ||--o{ notification : "account_id"
  account      ||--o{ activity     : "account_id"
  account      ||--o{ membership   : "account_id"
  membership   }o--|| organization : "organization_id"
  organization ||--o{ cluster      : "organization_id"
  notification }o--|| cluster      : "cluster_id"
  activity     }o--|| cluster      : "cluster_id"
  cluster      ||--o{ agent        : "cluster_id"
  organization ||--o{ runtime      : "organization_id"
  cluster      ||--o{ runtime      : "cluster_id"
  release      ||--o{ pipeline     : "target_release_id"
  runtime      ||--o{ pipeline     : "runtime_id"
  runtime      }o--|| release      : "current_release_id"
  account      ||--o{ pipeline     : "requester_account_id"
  pipeline     ||--o{ pipeline     : "previous_pipeline_id"
  action       }o--|| pipeline     : "pipeline_id"
  agent        ||--o{ action       : "execution_agent_id"
  stage        }o--|| action       : "action_id"
  release      }o--|| artifact     : "artifact_id"
  document     ||--o{ signature    : "document_id"
  signature    }o--|| account      : "account_id"
  signature    }o--|| certificate  : "certificate_id"
  document     ||--o{ document     : "replaced_document_id"

  account {
    uuidv7               id                "pk"
    timestamptz[3]       ts                ""
    timestamptz[3]       created_at        ""
    null[timestamptz[3]] deleted_at        ""
    varchar[100]         email             ""
    null[timestamptz[3]] email_verified_at ""
    enum[account_role]   role              ""
  }

  action {
    uuidv7               id                 "pk"
    timestamptz[3]       ts                 ""
    timestamptz[3]       created_at         ""
    null[timestamptz[3]] deleted_at         ""
    enum[action_type]    type               ""
    enum[action_status]  status             ""
    null[timestamptz[3]] started_at         ""
    null[timestamptz[3]] finished_at        ""
    null[text]           error_message      ""
    uuidv7               pipeline_id        "fk"
    uuidv7               execution_agent_id "fk"
  }

  activity {
    uuidv7                 id         "pk"
    timestamptz[3]         ts         ""
    timestamptz[3]         created_at ""
    enum[activity_type]    type       ""
    null[text]             message    ""
    null[jsonb]            metadata   ""
    null[uuidv7]           account_id "fk"
    uuidv7                 cluster_id "fk"
  }

  agent {
    uuidv7               id              "pk"
    timestamptz[3]       ts              ""
    timestamptz[3]       created_at      ""
    null[timestamptz[3]] deleted_at      ""
    enum[agent_status]   status          ""
    varchar[50]          version         ""
    null[timestamptz[3]] last_seen_at    ""
    null[text]           public_key      ""
    null[jsonb]          metadata        ""
    uuidv7               cluster_id      "fk"
  }

  artifact {
    uuidv7               id         "pk"
    timestamptz[3]       ts         ""
    timestamptz[3]       created_at ""
    null[timestamptz[3]] deleted_at ""
    enum[artifact_kind]  kind       ""
    varchar[100]         name       ""
    jsonb                metadata   ""
  }

  certificate {
    uuidv7                 id         "pk"
    timestamptz[3]         ts         ""
    timestamptz[3]         created_at ""
    null[timestamptz[3]]   deleted_at ""
    enum[certificate_kind] kind       ""
    text                   content    ""
    uuidv7                 account_id "fk"
  }

  cluster {
    uuidv7               id                 "pk"
    timestamptz[3]       ts                 ""
    timestamptz[3]       created_at         ""
    null[timestamptz[3]] deleted_at         ""
    enum[cluster_state]  state              ""
    null[timestamptz[3]] promoted_at        ""
    null[timestamptz[3]] legacy_at          ""
    varchar[100]         name               ""
    varchar[60]          namespace          ""
    null[varchar[50]]    provider           ""
    null[varchar[100]]   external_id        ""
    null[varchar[50]]    kubernetes_version ""
    jsonb                metadata           ""
    uuidv7               organization_id    "fk"
  }

  credential {
    uuidv7         id            "pk"
    timestamptz[3] ts            ""
    timestamptz[3] created_at    ""
    text           password_hash ""
    uuidv7         account_id    "fk"
  }

  document {
    uuidv7                id                   "pk"
    timestamptz[3]        ts                   ""
    timestamptz[3]        created_at           ""
    null[timestamptz[3]]  deleted_at           ""
    enum[document_kind]   kind                 ""
    enum[document_status] status               ""
    text                  title                ""
    text                  storage_key          ""
    text                  mime_type            ""
    bigint                file_size            ""
    text                  content_sha256       ""
    null[jsonb]           metadata             ""
    null[uuidv7]          replaced_document_id "fk"
  }

  invoice {
    uuidv7               id                 "pk"
    timestamptz[3]       ts                 ""
    timestamptz[3]       created_at         ""
    null[timestamptz[3]] deleted_at         ""
    enum[invoice_status] status             ""
    varchar[10]          currency           ""
    int                  total_cents        ""
    int                  tax_cents          ""
    int                  discount_cents     ""
    null[timestamptz[3]] due_at             ""
    null[timestamptz[3]] paid_at            ""
    varchar[100]         stripe_invoice_key ""
    uuidv7               subscription_id    "fk"
  }

  membership {
    uuidv7                id              "pk"
    timestamptz[3]        ts              ""
    enum[membership_role] role            ""
    uuidv7                account_id      "fk"
    uuidv7                organization_id "fk"
  }

  notification {
    uuidv7                    id          "pk"
    timestamptz[3]            ts          ""
    timestamptz[3]            created_at  ""
    null[timestamptz[3]]      deleted_at  ""
    enum[notification_kind]   kind        ""
    enum[notification_level]  level       ""
    enum[notification_status] status      ""
    text                      message     ""
    null[jsonb]               metadata    ""
    null[uuidv7]              artifact_id "fk"
    uuidv7                    cluster_id  "fk"
    uuidv7                    account_id  "fk"
  }

  organization {
    uuidv7               id                 "pk"
    timestamptz[3]       ts                 ""
    timestamptz[3]       created_at         ""
    null[timestamptz[3]] deleted_at         ""
    varchar[100]         name               ""
    varchar[100]         slug               ""
    jsonb                config             ""
    uuidv7               creator_account_id "fk"
  }

  payment {
    uuidv7               id                        "pk"
    timestamptz[3]       ts                        ""
    timestamptz[3]       created_at                ""
    null[timestamptz[3]] deleted_at                ""
    enum[payment_status] status                    ""
    varchar[10]          currency                  ""
    int                  amount_cents              ""
    varchar[100]         stripe_payment_intent_key ""
    null[varchar[100]]   failure_code              ""
    null[text]           failure_message           ""
    null[timestamptz[3]] processed_at              ""
    uuidv7               invoice_id                "fk"
  }

  pipeline {
    uuidv7                id                   "pk"
    timestamptz[3]        ts                   ""
    timestamptz[3]        created_at           ""
    null[timestamptz[3]]  deleted_at           ""
    enum[pipeline_type]   type                 ""
    enum[pipeline_status] status               ""
    null[jsonb]           payload              ""
    null[timestamptz[3]]  started_at           ""
    null[timestamptz[3]]  finished_at          ""
    null[text]            error_message        ""
    null[uuidv7]          target_release_id    "fk"
    uuidv7                runtime_id           "fk"
    uuidv7                requester_account_id "fk"
    null[uuidv7]          previous_pipeline_id "fk"
  }

  plan {
    uuidv7                 id          "pk"
    timestamptz[3]         ts          ""
    timestamptz[3]         created_at  ""
    null[timestamptz[3]]   deleted_at  ""
    varchar[50]            code        ""
    varchar[100]           name        ""
    enum[plan_interval]    interval    ""
    varchar[10]            currency    ""
    int                    price_cents ""
    jsonb                  config      ""
  }

  profile {
    uuidv7              id          "pk"
    timestamptz[3]      ts          ""
    null[varchar[100]]  given_name  ""
    null[varchar[100]]  family_name ""
    enum[profile_theme] theme       ""
    varchar[10]         language    ""
    varchar[50]         timezone    ""
    uuidv7              account_id  "fk"
  }

  release {
    uuidv7                id           "pk"
    timestamptz[3]        ts           ""
    timestamptz[3]        created_at   ""
    null[timestamptz[3]]  deleted_at   ""
    varchar[50]           version      ""
    enum[release_channel] channel      ""
    bool                  recommended  ""
    null[text]            notes        ""
    null[timestamptz[3]]  published_at ""
    jsonb                 metadata     ""
    uuidv7                artifact_id  "fk"
  }

  runtime {
    uuidv7               id                 "pk"
    timestamptz[3]       ts                 ""
    timestamptz[3]       created_at         ""
    null[timestamptz[3]] deleted_at         ""
    enum[runtime_state]  state              ""
    bool                 readonly           ""
    null[timestamptz[3]] last_deployed_at   ""
    jsonb                config             ""
    null[uuidv7]         current_release_id "fk"
    uuidv7               organization_id    "fk"
    uuidv7               cluster_id         "fk"
  }

  signature {
    uuidv7                id             "pk"
    timestamptz[3]        ts             ""
    timestamptz[3]        created_at     ""
    enum[signature_state] state          ""
    null[timestamptz[3]]  signed_at      ""
    null[text]            failure_reason ""
    null[text]            value          ""
    null[text]            hash           ""
    null[jsonb]           metadata       ""
    uuidv7                document_id    "fk"
    uuidv7                account_id     "fk"
    null[uuidv7]          certificate_id "fk"
  }

  stage {
    uuidv7               id          "pk"
    timestamptz[3]       ts          ""
    timestamptz[3]       created_at  ""
    null[timestamptz[3]] deleted_at  ""
    varchar[100]         name        ""
    int                  position    ""
    enum[stage_status]   status      ""
    null[timestamptz[3]] started_at  ""
    null[timestamptz[3]] finished_at ""
    null[text]           summary     ""
    null[jsonb]          output_meta ""
    uuidv7               action_id   "fk"
  }

  subscription {
    uuidv7                    id                        "pk"
    timestamptz[3]            ts                        ""
    timestamptz[3]            created_at                ""
    null[timestamptz[3]]      deleted_at                ""
    enum[subscription_status] status                    ""
    null[timestamptz[3]]      trial_ends_at             ""
    null[timestamptz[3]]      current_period_start_at   ""
    null[timestamptz[3]]      current_period_end_at     ""
    null[timestamptz[3]]      canceled_at               ""
    varchar[50]               currency                  ""
    int                       price_cents               ""
    varchar[100]              stripe_customer_key       ""
    varchar[100]              stripe_subscription_key   ""
    uuidv7                    organization_id           "fk"
    uuidv7                    plan_id                   "fk"
  }
