---
config:
  layout: elk
---
erDiagram
  direction LR
  subscription            }o--|| organization            : "organization_id"
  subscription_invoice    }o--|| subscription            : "subscription_id"
  subscription_payment    }o--|| subscription_invoice    : "subscription_invoice_id"
  account_certificate     }o--|| account                 : "account_id"
  account_profile         ||--|| account                 : "account_id"
  plan                    ||--o{ subscription            : "plan_id"
  account_credential      |o--|| account                 : "account_id"
  account                 ||--o{ account_notification    : "account_id"
  account                 ||--o{ account_activity        : "account_id"
  account                 ||--o{ organization_membership : "account_id"
  organization_membership }o--|| organization            : "organization_id"
  account                 ||--o{ organization_invite     : "creator_account_id"
  organization_invite     }o--|| organization            : "organization_id"
  organization            ||--o{ cluster                 : "organization_id"
  account_notification    }o--|| cluster                 : "cluster_id"
  account_activity        }o--|| cluster                 : "cluster_id"
  cluster                 ||--o{ cluster_agent           : "cluster_id"
  organization            ||--o{ cluster_runtime         : "organization_id"
  cluster                 ||--o{ cluster_runtime         : "cluster_id"
  artifact_release        ||--o{ pipeline                : "target_artifact_release_id"
  cluster_runtime         ||--o{ pipeline                : "cluster_runtime_id"
  cluster_runtime         }o--|| artifact_release        : "current_artifact_release_id"
  account                 ||--o{ pipeline                : "requester_account_id"
  pipeline                ||--o{ pipeline                : "previous_pipeline_id"
  pipeline_action         }o--|| pipeline                : "pipeline_id"
  cluster_agent           ||--o{ pipeline_action         : "execution_cluster_agent_id"
  pipeline_action_stage   }o--|| pipeline_action         : "pipeline_action_id"
  artifact_release        }o--|| artifact                : "artifact_id"
  document                ||--o{ document_signature      : "document_id"
  document_signature      }o--|| account_certificate     : "account_certificate_id"
  document                ||--o{ document                : "replaced_document_id"
  cluster                 ||--o{ cluster_agent_enrollment : "cluster_id"
  document                }o--|| organization            : "organization_id"
  
  account {
    uuidv7               id                "pk"
    timestamptz[3]       ts                 ""
    timestamptz[3]       created_at         ""
    null[timestamptz[3]] deleted_at         ""
    varchar[100]         email              ""
    null[timestamptz[3]] email_verified_at  ""
    enum[account_role]   role               ""
  }

  pipeline_action {
    uuidv7                       id                         "pk"
    timestamptz[3]               ts                          ""
    timestamptz[3]               created_at                  ""
    null[timestamptz[3]]         deleted_at                  ""
    enum[pipeline_action_kind]   kind                        ""
    enum[pipeline_action_status] status                      ""
    null[timestamptz[3]]         started_at                  ""
    null[timestamptz[3]]         finished_at                 ""
    null[text]                   error_message               ""
    uuidv7                       pipeline_id                "fk"
    null[uuidv7]                 execution_cluster_agent_id "fk"
  }

  account_activity {
    uuidv7                      id              "pk"
    timestamptz[3]              ts               ""
    timestamptz[3]              created_at       ""
    enum[account_activity_kind] kind             ""
    null[text]                  message          ""
    null[jsonb]                 metadata         ""
    null[uuidv7]                account_id      "fk"
    null[uuidv7]                organization_id "fk"
    uuidv7                      cluster_id      "fk"
  }

  cluster_agent {
    uuidv7                     id           "pk"
    timestamptz[3]             ts            ""
    timestamptz[3]             created_at    ""
    null[timestamptz[3]]       deleted_at    ""
    enum[cluster_agent_status] status        ""
    varchar[50]                version       ""
    null[timestamptz[3]]       last_seen_at  ""
    text                       public_key    ""
    null[jsonb]                metadata      ""
    uuidv7                     cluster_id   "fk"
  }

  artifact {
    uuidv7               id         "pk"
    timestamptz[3]       ts          ""
    timestamptz[3]       created_at  ""
    null[timestamptz[3]] deleted_at  ""
    enum[artifact_kind]  kind        ""
    varchar[100]         name        ""
    jsonb                metadata    ""
  }

  account_certificate {
    uuidv7               id              "pk"
    timestamptz[3]       ts               ""
    timestamptz[3]       created_at       ""
    null[timestamptz[3]] deleted_at       ""
    timestamptz[3]       expires_at       ""
    varchar[100]         display_name     ""
    varchar[14]          document_number  ""
    varchar[100]         owner_name       ""
    text                 thumbprint       ""
    boolean              is_active        ""
    uuidv7               account_id      "fk"
  }

  cluster {
    uuidv7               id                 "pk"
    timestamptz[3]       ts                  ""
    timestamptz[3]       created_at          ""
    null[timestamptz[3]] deleted_at          ""
    enum[cluster_state]  state               ""
    null[timestamptz[3]] promoted_at         ""
    null[timestamptz[3]] legacy_at           ""
    varchar[100]         name                ""
    varchar[60]          namespace           ""
    null[varchar[50]]    provider            ""
    null[varchar[100]]   external_id         ""
    null[varchar[50]]    kubernetes_version  ""
    jsonb                metadata            ""
    uuidv7               organization_id    "fk"
  }

  account_credential {
    uuidv7         id            "pk"
    timestamptz[3] ts             ""
    timestamptz[3] created_at     ""
    text           password_hash  ""
    uuidv7         account_id    "fk"
  }

  document {
    uuidv7                id                   "pk"
    timestamptz[3]        ts                    ""
    timestamptz[3]        created_at            ""
    null[timestamptz[3]]  deleted_at            ""
    enum[document_kind]   kind                  ""
    enum[document_status] status                ""
    text                  title                 ""
    text                  storage_key           ""
    text                  mimetype              ""
    bigint                file_size             ""
    text                  content_sha256        ""
    null[jsonb]           metadata              ""
    null[uuidv7]          replaced_document_id "fk"
    uuidv7                organization_id      "fk"
    uuidv7                creator_account_id   "fk"
  }

  organization_invite {
    uuidv7                             id                 "pk"
    timestamptz[3]                     ts                  ""
    timestamptz[3]                     created_at          ""
    char[6]                            code                ""
    varchar[100]                       email               ""
    enum[organization_membership_role] role                ""
    enum[organization_invite_status]   status              ""
    timestamptz[3]                     expires_at          ""
    timestamptz[3]                     accepted_at         ""
    uuidv7                             organization_id    "fk"
    uuidv7                             creator_account_id "fk"
  }

  subscription_invoice {
    uuidv7                            id                 "pk"
    timestamptz[3]                    ts                  ""
    timestamptz[3]                    created_at          ""
    null[timestamptz[3]]              deleted_at          ""
    enum[subscription_invoice_status] status              ""
    varchar[10]                       currency            ""
    int                               total_cents         ""
    int                               tax_cents           ""
    int                               discount_cents      ""
    null[timestamptz[3]]              due_at              ""
    null[timestamptz[3]]              paid_at             ""
    varchar[100]                      stripe_invoice_key  ""
    uuidv7                            subscription_id    "fk"
  }

  organization_membership {
    uuidv7                             id              "pk"
    timestamptz[3]                     ts               ""
    timestamptz[3]                     created_at       ""
    enum[organization_membership_role] role             ""
    uuidv7                             account_id      "fk"
    uuidv7                             organization_id "fk"
  }

  account_notification {
    uuidv7                            id          "pk"
    timestamptz[3]                    ts           ""
    timestamptz[3]                    created_at   ""
    null[timestamptz[3]]              deleted_at   ""
    enum[account_notification_kind]   kind         ""
    enum[account_notification_level]  level        ""
    enum[account_notification_status] status       ""
    text                              message      ""
    null[jsonb]                       metadata     ""
    null[uuidv7]                      artifact_id "fk"
    uuidv7                            cluster_id  "fk"
    uuidv7                            account_id  "fk"
  }

  organization {
    uuidv7               id                 "pk"
    timestamptz[3]       ts                  ""
    timestamptz[3]       created_at          ""
    null[timestamptz[3]] deleted_at          ""
    varchar[100]         name                ""
    varchar[100]         slug                ""
    jsonb                config              ""
    uuidv7               creator_account_id "fk"
  }

  subscription_payment {
    uuidv7                            id                        "pk"
    timestamptz[3]                    ts                         ""
    timestamptz[3]                    created_at                 ""
    null[timestamptz[3]]              deleted_at                 ""
    enum[subscription_payment_status] status                     ""
    varchar[10]                       currency                   ""
    int                               amount_cents               ""
    varchar[100]                      stripe_payment_intent_key  ""
    null[varchar[100]]                failure_code               ""
    null[text]                        failure_message            ""
    null[timestamptz[3]]              processed_at               ""
    uuidv7                            subscription_invoice_id   "fk"
  }

  pipeline {
    uuidv7                id                         "pk"
    timestamptz[3]        ts                          ""
    timestamptz[3]        created_at                  ""
    null[timestamptz[3]]  deleted_at                  ""
    enum[pipeline_kind]   kind                        ""
    enum[pipeline_status] status                      ""
    null[jsonb]           payload                     ""
    null[timestamptz[3]]  started_at                  ""
    null[timestamptz[3]]  finished_at                 ""
    null[text]            error_message               ""
    null[uuidv7]          target_artifact_release_id "fk"
    uuidv7                cluster_runtime_id         "fk"
    uuidv7                requester_account_id       "fk"
    uuidv7                organization_id            "fk"
    null[uuidv7]          previous_pipeline_id       "fk"
  }

  plan {
    uuidv7               id          "pk"
    timestamptz[3]       ts           ""
    timestamptz[3]       created_at   ""
    null[timestamptz[3]] deleted_at   ""
    varchar[50]          code         ""
    varchar[100]         name         ""
    enum[plan_interval]  interval     ""
    varchar[10]          currency     ""
    int                  price_cents  ""
    jsonb                config       ""
  }

  account_profile {
    uuidv7                      id                       "pk"
    timestamptz[3]              ts                        ""
    null[varchar[100]]          given_name                ""
    null[varchar[100]]          family_name               ""
    varchar[10]                 language                  ""
    varchar[50]                 timezone                  ""
    uuidv7                      account_id               "fk"
  }

  account_preference {
    uuidv7                         id                           "pk"
    timestamptz[3]                 ts                            ""
    enum[account_preference_theme] theme                         ""
    boolean                        notify_on_pipeline_success    ""
    boolean                        notify_on_infra_alerts        ""
    uuidv7                         account_id                   "fk"
  }

  artifact_release {
    uuidv7                         id           "pk"
    timestamptz[3]                 ts            ""
    timestamptz[3]                 created_at    ""
    null[timestamptz[3]]           deleted_at    ""
    varchar[50]                    version       ""
    enum[artifact_release_channel] channel       ""
    bool                           recommended   ""
    null[text]                     notes         ""
    null[timestamptz[3]]           published_at  ""
    jsonb                          metadata      ""
    uuidv7                         artifact_id  "fk"
  }

  cluster_runtime {
    uuidv7                      id                          "pk"
    timestamptz[3]              ts                           ""
    timestamptz[3]              created_at                   ""
    null[timestamptz[3]]        deleted_at                   ""
    enum[cluster_runtime_state] state                        ""
    bool                        readonly                     ""
    null[timestamptz[3]]        last_deployed_at             ""
    jsonb                       config                       ""
    null[uuidv7]                current_artifact_release_id "fk"
    uuidv7                      cluster_id                  "fk"
  }

  document_signature {
    uuidv7                         id                     "pk"
    timestamptz[3]                 ts                      ""
    timestamptz[3]                 created_at              ""
    enum[document_signature_state] state                   ""
    null[timestamptz[3]]           signed_at               ""
    null[text]                     failure_reason          ""
    null[text]                     value                   ""
    null[text]                     hash                    ""
    null[jsonb]                    metadata                ""
    uuidv7                         document_id            "fk"
    uuidv7                         account_certificate_id "fk"
    uuidv7                         account_id             "fk"
  }

  pipeline_action_stage {
    uuidv7                             id                 "pk"
    timestamptz[3]                     ts                  ""
    timestamptz[3]                     created_at          ""
    null[timestamptz[3]]               deleted_at          ""
    varchar[100]                       name                ""
    int                                position            ""
    enum[pipeline_action_stage_status] status              ""
    null[timestamptz[3]]               started_at          ""
    null[timestamptz[3]]               finished_at         ""
    null[text]                         summary             ""
    null[jsonb]                        output_meta         ""
    uuidv7                             pipeline_action_id "fk"
  }

  subscription {
    uuidv7                    id                        "pk"
    timestamptz[3]            ts                         ""
    timestamptz[3]            created_at                 ""
    null[timestamptz[3]]      deleted_at                 ""
    enum[subscription_status] status                     ""
    null[timestamptz[3]]      trial_ends_at              ""
    null[timestamptz[3]]      current_period_start_at    ""
    null[timestamptz[3]]      current_period_end_at      ""
    null[timestamptz[3]]      canceled_at                ""
    varchar[50]               currency                   ""
    int                       price_cents                ""
    varchar[100]              stripe_customer_key        ""
    varchar[100]              stripe_subscription_key    ""
    uuidv7                    organization_id           "fk"
    uuidv7                    plan_id                   "fk"
  }

  cluster_agent_enrollment {
    uuidv7           id                 "pk"
    timestamptz[3]   ts                  ""
    timestamptz[3]   created_at          ""
    char[32]         token               ""
    timestamptz[3]   expires_at          ""
    bool             used                ""
    uuidv7           cluster_id         "fk"
    uuidv7           creator_account_id "fk"
  }